name: cd-cloudrun
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.example.com
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIP }}
          service_account: ${{ secrets.GCP_SA }}
      - uses: google-github-actions/setup-gcloud@v2
      - name: Build & Push (Artifact Registry)"
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev -q
          docker build -t $REGION-docker.pkg.dev/$PROJ/app/web:${{ github.sha }} .
          docker push $REGION-docker.pkg.dev/$PROJ/app/web:${{ github.sha }}
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy app --image $REGION-docker.pkg.dev/$PROJ/app/web:${{ github.sha }} --region $REGION --allow-unauthenticated
