name: cd-k8s
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: { name: staging }
    steps:
      - uses: actions/checkout@v4
      - name: Acquire kubeconfig (provider-specific)
        run: ./scripts/k8s_auth.sh
      - name: Helm upgrade/install
        run: |
          helm upgrade --install app ./chart             --namespace staging             --create-namespace             --set image.tag=${{ github.sha }}
