name: cd-cloudrun
on:
  push:
    branches: [main]
    paths:
      - 'node-demo/**'  # 只有 node-demo 變更時才觸發

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGION: asia-east1  # 設定您的區域
      PROJ: your-project-id  # 設定您的專案 ID
    steps:
      - uses: actions/checkout@v4
      
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # 使用 Service Account Key
      
      - uses: google-github-actions/setup-gcloud@v2
      
      - name: Build & Push to Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev -q
          docker build -t $REGION-docker.pkg.dev/$PROJ/app/web:${{ github.sha }} .
          docker push $REGION-docker.pkg.dev/$PROJ/app/web:${{ github.sha }}
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy node-demo-app \
            --image $REGION-docker.pkg.dev/$PROJ/app/web:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --memory 512Mi \
            --cpu 1 \
            --max-instances 10