name: ci-matrix
on: [push, pull_request]
jobs:
  node:
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      
      - run: npm install
        working-directory: node-demo
      - run: npm ci
        working-directory: node-demo
      - run: npm test --ci
        working-directory: node-demo

  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
      - name: Cache vendor
        uses: actions/cache@v4
        with:
          path: php-demo/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('php-demo/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - run: composer install --no-interaction --prefer-dist
        working-directory: php-demo
      - run: ./vendor/bin/phpunit --colors=always
        working-directory: php-demo

  all-green:
    runs-on: ubuntu-latest
    needs: [node, php]
    steps:
      - run: echo "All test jobs passed."
